version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_service
    command: redis-server --requirepass ${REDIS_PASSWORD}  # Usa la variable de entorno
    networks:
      - internal_net
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}  # Define la variable de entorno en el servicio Redis
  
  backend:
    build: .
    container_name: backend_service
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}  # Usa la variable de entorno también en el backend
    depends_on:
      - redis
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge
