services:
  redis:
    image: redis:latest
    container_name: redis_service
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - internal_net
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  backend:
    build: .
    container_name: backend_service
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis
    networks:
      - internal_net
    volumes:
      - .:/app  # 🔥 Montamos el código fuente dentro del contenedor
      - /app/node_modules  # 🔥 Evita sobrescribir node_modules
      - /app/dist  # 🔥 Asegura que el build no sea sobreescrito
    command: sh -c "npm run build && node dist/index.js"  # 🔥 Ejecutamos `npm run build` antes de iniciar la app

networks:
  internal_net:
    driver: bridge
