version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_service
    ports:
      - "6379:6379"   # Expone el puerto 6379 del contenedor
    networks:
      - app_network

  backend:
    build: .
    container_name: backend_service
    ports:
      - "3000:3000"   # Expone el puerto 3000 del backend
    environment:
      REDIS_HOST: redis   # Variable de entorno que indica el nombre del servicio redis
      REDIS_PORT: 6379
    depends_on:
      - redis   # Asegura que el servicio redis esté levantado antes de backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
